apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: quarkus-0423
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-0423 
  name: quarkus-0423
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: quarkus-0423 
